"""
Build a domain text corpus for training a Metro-ASR language head.

A language head only needs text. This script assembles one from three sources:

  1. REAL in-domain text pulled from HuggingFace (Egyptian medical chat/QA,
     Egyptian Arabic Wikipedia filtered to technical articles).
  2. REAL Arabic-English code-switching text, which teaches the model how
     speakers actually move between the two languages.
  3. SYNTHESISED Egyptian-dialect code-switching sentences, generated by
     dropping a broad inventory of domain terms into Egyptian carrier
     phrases. This is what supplies n-grams like "ال presentation" or
     "chest x-ray" that no public Arabic corpus contains.

Source 3 is the part you would write yourself for your own domain: replace
TECHNICAL_TERMS / MEDICAL_TERMS with your product names, drug names, station
names or ticker symbols and re-run.

Usage:
    python scripts/build_domain_corpus.py --domain technical --out corpora/technical.txt
    python scripts/build_domain_corpus.py --domain medical   --out corpora/medical.txt
"""

import argparse
import os
import random
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from metro_asr.utils import enable_utf8_stdout

enable_utf8_stdout()

from metro_asr.data.dataset import normalize_arabic_text

# ─────────────────────────────────────────────────────────────────────────────
# Egyptian-dialect carrier phrases. "{T}" is where an English term lands.
# The bare Arabic article before an English word ("ال meeting") is the
# characteristic surface form of Egyptian Arabic-English code-switching.
# ─────────────────────────────────────────────────────────────────────────────
CARRIERS = [
    "الاسبوع اللي فات اتعلمت حاجات كتير عن ال {T}",
    "زمايلي في الشركة بيهتموا بال {T} جدا",
    "الموضوع ده محتاج {T} كويس",
    "خلينا نعمل ال {T} الاول",
    "هو ال {T} ده بيشتغل ازاي",
    "انا شغال على ال {T} من امبارح",
    "لازم نراجع ال {T} قبل ما نسلم",
    "فيه {T} جديدة نزلت الاسبوع ده",
    "اقدر اعمل {T} بسهولة",
    "ده كان في ال {T} بتاع السنة اللي فاتت",
    "بص يا سيدي ال {T} دي محتاجة وقت",
    "احنا اتكلمنا عن ال {T} في الاجتماع",
    "انا عايز افهم ال {T} ده كويس",
    "المفروض ال {T} يخلص النهاردة",
    "هو ده اللي بيحصل في ال {T}",
    "ياريت تبعتلي ال {T} على الايميل",
    "انا مش فاهم ال {T} ده",
    "خد بالك من ال {T} دي",
    "الناس بتقول ان ال {T} صعب",
    "بعد ما خلصت ال {T} رحت البيت",
    "و ده كان بخصوص ال {T}",
    "احنا محتاجين {T} تانية",
    "ال {T} ده مهم جدا بالنسبة لينا",
    "انا اتعلمت ال {T} من ال course",
    "فيه مشكلة في ال {T}",
    "ممكن تشرحلي ال {T} تاني",
    "ال {T} بتاعنا شغال تمام",
    "انا كنت بشتغل على ال {T} ده",
    "كل حاجة في ال {T} تمام",
    "المشكلة كانت في ال {T} نفسه",
]

CONNECTORS = [
    "و بعدين", "بس", "يعني", "برضه", "كمان", "علشان كده", "الحقيقة",
    "بصراحة", "فعلا", "طبعا", "على فكرة", "المهم", "و اخيرا",
]

# ─────────────────────────────────────────────────────────────────────────────
# Broad domain inventories. These are general vocabularies for the domain, not
# a transcription of any particular audio.
# ─────────────────────────────────────────────────────────────────────────────
TECHNICAL_TERMS = [
    # workplace / study
    "presentation", "meeting", "quiz", "course", "assignment", "project", "deadline",
    "interview", "internship", "intern", "offer", "team", "manager", "startup",
    "remotely", "remote", "onsite", "freelance", "portfolio", "resume", "cv",
    "workshop", "session", "lecture", "lab", "exam", "midterm", "final",
    "conference", "seminar", "certificate", "training", "bootcamp", "mentor",
    # AI / ML
    "machine learning", "deep learning", "neural network", "convolutional neural network",
    "cnn", "rnn", "lstm", "transformer", "attention", "embedding", "fine tuning",
    "training", "dataset", "model", "inference", "gradient descent", "backpropagation",
    "overfitting", "regularization", "dropout", "batch size", "learning rate", "epoch",
    "accuracy", "precision", "recall", "loss function", "optimizer", "classification",
    "regression", "clustering", "computer vision", "natural language processing", "nlp",
    "speech recognition", "speech ai", "arabic nlp", "large language model", "llm",
    "prompt", "token", "tokenizer", "encoder", "decoder", "reinforcement learning",
    "supervised learning", "unsupervised learning", "feature extraction", "data augmentation",
    # software engineering
    "code", "coding", "programming", "software", "hardware", "algorithm", "data structure",
    "function", "variable", "loop", "array", "class", "object", "library", "framework",
    "api", "endpoint", "database", "query", "server", "client", "backend", "frontend",
    "full stack", "deployment", "production", "staging", "testing", "unit test", "debugging",
    "bug", "issue", "feature", "release", "version", "repository", "commit", "pull request",
    "merge", "branch", "git", "github", "docker", "kubernetes", "cloud", "aws", "azure",
    "linux", "windows", "terminal", "script", "package", "dependency", "compiler",
    "python", "java", "javascript", "typescript", "html", "css", "sql", "react", "node",
    "pytorch", "tensorflow", "numpy", "pandas", "notebook", "colab", "gpu", "cpu", "ram",
    "latency", "throughput", "performance", "optimization", "cache", "memory", "storage",
    "security", "encryption", "authentication", "token", "password", "firewall",
    "network", "protocol", "request", "response", "json", "config", "log", "pipeline",
    "microservice", "architecture", "scalability", "monitoring", "dashboard", "analytics",
]

MEDICAL_TERMS = [
    # symptoms
    "headache", "severe headache", "migraine", "dizziness", "nausea", "vomiting", "fever",
    "cough", "chest pain", "shortness of breath", "fatigue", "weakness", "swelling",
    "inflammation", "infection", "rash", "allergy", "pain", "cramps", "bleeding",
    "high blood pressure", "low blood pressure", "palpitations", "insomnia", "anxiety",
    # tests / imaging
    "blood test", "blood sugar", "cbc", "urine test", "x ray", "chest x ray", "ct scan",
    "mri", "mri scan", "ultrasound", "echo", "ecg", "ekg", "endoscopy", "biopsy",
    "screening", "lab results", "scan", "imaging", "culture", "swab", "sample",
    "cholesterol", "hemoglobin", "white blood cells", "platelets", "thyroid function",
    # systems / anatomy
    "respiratory tract", "respiratory system", "digestive system", "nervous system",
    "cardiovascular", "neurological", "neurological examination", "immune system",
    "liver", "kidney", "lungs", "heart", "brain", "stomach", "intestine", "thyroid",
    "spine", "joint", "muscle", "artery", "vein", "nerve",
    # conditions
    "diabetes", "hypertension", "asthma", "pneumonia", "bronchitis", "anemia", "ulcer",
    "arthritis", "osteoporosis", "gastritis", "sinusitis", "tonsillitis", "hepatitis",
    "bacterial infection", "viral infection", "chronic condition", "acute condition",
    "serious condition", "side effect", "complication", "diagnosis", "prognosis",
    # care
    "treatment", "therapy", "physiotherapy", "medication", "antibiotic", "painkiller",
    "dose", "dosage", "prescription", "injection", "vaccine", "surgery", "operation",
    "consultation", "follow up", "examination", "physical examination", "checkup",
    "emergency", "icu", "clinic", "hospital", "specialist", "referral", "patient",
    "doctor", "nurse", "recovery", "rehabilitation", "monitoring", "symptoms",
]


def synth_sentences(terms, n_sentences, seed=42):
    """Drop domain terms into Egyptian carrier phrases, with light variation."""
    rng = random.Random(seed)
    out = []
    for _ in range(n_sentences):
        term = rng.choice(terms)
        sent = rng.choice(CARRIERS).replace("{T}", term)
        if rng.random() < 0.35:
            sent = rng.choice(CONNECTORS) + " " + sent
        if rng.random() < 0.25:
            sent = sent + " " + rng.choice(CONNECTORS) + " " + rng.choice(terms)
        out.append(sent)
    return out


def term_pair_sentences(terms, n_sentences, seed=43):
    """Sentences pairing two domain terms, so term-to-term n-grams exist too."""
    rng = random.Random(seed)
    joiners = ["و", "مع", "بالاضافة ل", "و كمان", "او"]
    out = []
    for _ in range(n_sentences):
        a, b = rng.choice(terms), rng.choice(terms)
        if a == b:
            continue
        out.append(f"ال {a} {rng.choice(joiners)} ال {b} مهمين جدا")
        out.append(f"احنا بنستخدم ال {a} و ال {b} في الشغل")
    return out


def read_lines(path, limit=None):
    if not os.path.exists(path):
        print(f"  ! missing {path} — skipping")
        return []
    out = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                out.append(line)
            if limit and len(out) >= limit:
                break
    return out


def split_sentences(text, max_words=40):
    """Break long articles/answers into sentence-sized chunks."""
    parts = re.split(r"[.!?؟،\n]+", text)
    out = []
    for p in parts:
        words = p.split()
        if 3 <= len(words) <= max_words:
            out.append(" ".join(words))
        elif len(words) > max_words:
            for i in range(0, len(words), max_words):
                chunk = words[i:i + max_words]
                if len(chunk) >= 3:
                    out.append(" ".join(chunk))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", choices=["technical", "medical", "general"], required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--raw-dir", default="corpora_raw")
    ap.add_argument("--synth", type=int, default=60000, help="synthesised sentences")
    ap.add_argument("--cs-repeat", type=int, default=3, help="repeats of code-switching text")
    ap.add_argument("--max-real-docs", type=int, default=25000,
                    help="cap on real in-domain documents, to bound LM training memory")
    args = ap.parse_args()

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    R = args.raw_dir
    corpus = []

    print(f"building {args.domain} corpus")

    # ---- real in-domain text -------------------------------------------
    if args.domain == "medical":
        for fname in ["egy_medical_chat.txt", "egy_medical_qa.txt"]:
            raw = read_lines(os.path.join(R, fname), args.max_real_docs)
            chunks = [c for t in raw for c in split_sentences(t)]
            print(f"  real  {fname:<24} {len(raw):>7} docs -> {len(chunks):>8} sentences")
            corpus += chunks
        terms = MEDICAL_TERMS

    elif args.domain == "technical":
        raw = read_lines(os.path.join(R, "arz_wiki_tech.txt"), args.max_real_docs)
        chunks = [c for t in raw for c in split_sentences(t)]
        print(f"  real  {'arz_wiki_tech.txt':<24} {len(raw):>7} docs -> {len(chunks):>8} sentences")
        corpus += chunks
        terms = TECHNICAL_TERMS

    else:
        terms = []

    # ---- real code-switching text ---------------------------------------
    cs = read_lines(os.path.join(R, "code_switching.txt"))
    cs_chunks = [c for t in cs for c in split_sentences(t)]
    corpus += cs_chunks * args.cs_repeat
    print(f"  real  {'code_switching.txt':<24} {len(cs):>7} docs -> "
          f"{len(cs_chunks) * args.cs_repeat:>8} sentences (x{args.cs_repeat})")

    # ---- synthesised domain code-switching ------------------------------
    if terms:
        synth = synth_sentences(terms, args.synth)
        pairs = term_pair_sentences(terms, args.synth // 4)
        corpus += synth + pairs
        print(f"  synth {'domain code-switching':<24} {len(terms):>7} terms -> "
              f"{len(synth) + len(pairs):>8} sentences")

    # ---- normalise exactly as the ASR pipeline does ----------------------
    print("  normalising")
    cleaned = []
    for line in corpus:
        line = normalize_arabic_text(line).lower().strip()
        if len(line.split()) >= 3:
            cleaned.append(line)

    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        for line in cleaned:
            f.write(line + "\n")

    words = sum(len(l.split()) for l in cleaned)
    print(f"\n  -> {args.out}")
    print(f"     {len(cleaned):,} sentences | {words:,} words | "
          f"{os.path.getsize(args.out) / 1e6:.1f} MB")


if __name__ == "__main__":
    main()
